### ISSUE TITLE
4.29.0 and typedefs cause an error with createXStateContext.ts

### ISSUE THREAD

**Issue by eisen-develops** [mattpocock/xstate-next-boilerplate#2]
With the new schema and typedefs I was getting a error, I noticed it was expecting a StateMachine with typegendisabled as the last type. I've fixed it  here https://github.com/1ceb3rg/xstate-next-boilerplate/commit/1e0d8b73f94ed7c67894096168cd5f086fc50e6a . I  also changed ActorRefFrom to InterpreterFrom for the context, which solved my issue, but I'm not sure if it's the correct way.  I can make a pull request if you'd like.

**Comment by mattpocock** [comment]
Looks pretty good to me - could you PR this to this repo?

**Comment by VRspace4** [comment]
Thank you! This is exactly what I was looking for!

**Comment by mattpocock** [comment]
Closed! Thanks @1ceb3rg

**Comment by eisen-develops** [comment]
> Closed! Thanks @1ceb3rg

No problem, thanks for all the hard work on XState!
